### ISSUE TITLE
This plugin not work in version 1.9.3

### ISSUE THREAD

**Issue by hlyang1992** [danmichaelo/crystallography#1]
This plugin is very powerful. However, it doesn't work in new version 1.9.3.

**Comment by danmichaelo** [comment]
Did you test that it worked in 1.9.2, but not in 1.9.3? Did you get any error messages?

**Comment by hlyang1992** [comment]
I don't test it in 1.9.2. I will give you error informations later. Could you please help me understand the math of project  operation? I don't know Tcl. Thank you very much.

**Comment by danmichaelo** [comment]
It's been too long since I worked with all this stuff, but the code is quite well documented and Tcl is quite readable once you learn a few syntactic quirks, for instance that a function call do not involve parenthesis :) For the vector/matrix operations, I tried to use the functions provided by VMD (documented [here](http://www.ks.uiuc.edu/Research/vmd/current/ug/node192.html)). To understand projection, a textbook on linear algebra should help you, perhaps coupled with one on crystallography?

**Comment by danmichaelo** [comment]
Just tested it with 1.9.3 and it still worked. If you have more details, please let me know.
